# Generated by Django 4.1.2 on 2022-10-30 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcars', '0002_alter_car_model_alter_car_price_alter_car_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='model',
            new_name='my_model',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='type',
            new_name='my_type',
        ),
    ]
